export const GETALL_CART_ITEM_START = "GETALL_CART_ITEM_START"
export const GETALL_CART_ITEM_SUCCESS = "GETALL_CART_ITEM_SUCCESS"
export const GETALL_CART_ITEM_ERROR = "GETALL_CART_ITEM_ERROR"

export const ADD_ITEM_TOCART_START = "ADD_ITEM_TOCART_START"
export const ADD_ITEM_TOCART_SUCCESS = "ADD_ITEM_TOCART_SUCCESS"
export const ADD_ITEM_TOCART_ERROR = "ADD_ITEM_TOCART_ERROR"

export const DELETE_ITEM_TOCART_START = "DELETE_ITEM_TOCART_START"
export const DELETE_ITEM_TOCART_SUCCESS = "DELETE_ITEM_TOCART_SUCCESS"
export const DELETE_ITEM_TOCART_ERROR = "DELETE_ITEM_TOCART_ERROR"

export const DELETE_ALL_ITEM_FROM_CART_START = "DELETE_ALL_ITEM_FROM_CART_START"
export const DELETE_ALL_ITEM_FROM_CART_SUCCESS = "DELETE_ALL_ITEM_FROM_CART_SUCCESS"
export const DELETE_ALL_ITEM_FROM_CART_ERROR = "DELETE_ALL_ITEM_FROM_CART_ERROR"