// for Project Estimation
export const PROJECT_ESTIMATION_START = "PROJECT_ESTIMATION_START"
export const PROJECT_ESTIMATION_SUCCESS = "PROJECT_ESTIMATION_SUCCESS"
export const PROJECT_ESTIMATION_ERROR = "PROJECT_ESTIMATION_ERROR"
