 
export const REGISTER_AS_PROFESSIONAL_START = "REGISTER_AS_PROFESSIONAL_START"
export const REGISTER_AS_PROFESSIONAL_SUCCESS = "REGISTER_AS_PROFESSIONAL_SUCCESS"
export const REGISTER_AS_PROFESSIONAL_ERROR = "REGISTER_AS_PROFESSIONAL_ERROR"
