export const GETALL_SERVICES_START = "GETALL_SERVICES_START"
export const GETALL_SERVICES_SUCCESS = "GETALL_SERVICES_SUCCESS"
export const GETALL_SERVICES_ERROR = "GETALL_SERVICES_ERROR"

export const GET_SINGLE_SERVICE_START = "GET_SINGLE_SERVICE_START"
export const GET_SINGLE_SERVICE_SUCCESS = "GET_SINGLE_SERVICE_SUCCESS"
export const GET_SINGLE_SERVICE_ERROR = "GET_SINGLE_SERVICE_ERROR"

export const GET_SINGLE_CATEGORY_START = "GET_SINGLE_CATEGORY_START"
export const GET_SINGLE_CATEGORY_SUCCESS = "GET_SINGLE_CATEGORY_SUCCESS"
export const GET_SINGLE_CATEGORY_ERROR = "GET_SINGLE_CATEGORY_ERROR"

// 
export const GET_SERVICES_FOR_OPTIONS_START = "GET_SERVICES_FOR_OPTIONS_START"
export const GET_SERVICES_FOR_OPTIONS_SUCCESS = "GET_SERVICES_FOR_OPTIONS_SUCCESS"
export const GET_SERVICES_FOR_OPTIONS_ERROR = "GET_SERVICES_FOR_OPTIONS_ERROR"